language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
cache: 
  pip: true
  directories:
    - $HOME/nltk_data
install:
- pip install -r pip-req.txt
- python -c "import nltk; nltk.download('all')"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- coverage erase
- coverage run --source=nltk nltk/test/runtests.py
after_script:
- coverage xml --omit=nltk/test/*
- if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]];
  then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
deploy:
  provider: pypi
  on:
    tags: true
    python: '3.6'
  user: pppp
  password:
    secure: uyLz0crQNXlhrX3SI+zHQHbqOanTZmrm3EfgpzLvzBoR43CSfd+yXPmcLsDTEQAUHH5EnwhO7uST/KpDMIuh9fKXeu4e9ZKl/03TNzP7jejNl3QmtjA44ugUwPgRN2Dl/1/mTyHoo8GuwTUqBfKv5BS8+kRGo6Y4NJCLshyIbo8gjbYLja+LWSP6HlZVyI6EATcoimy95RKpsjV37V8qqm763OoMbRuh1yt15ev0VwTWSDR/fqD5MyUmDyXRiZ8lIyUMplfbS2Ux+jyeFvwXi3kqcbKOL3UAmqC8Y8GBY7FdCuSj6XSgd3vguR6wknlgY978SoCbq60D+PfbBCKKFlMsAALVgC+CRu1yFgFD7YiZ5kjFVnPVmuiQN5Hyfsis1HG894jRuozuhXVfFYNBA3YrD/olEcYNzlnSmpNdB1H8BJYOmGwBIKhZrVH0qSYW+I9fX+qM5KRhpDMPGqbZcuV70gIVu+nDPBEGbodFUNQZ40AC01Vq8KNF2zEb9wuSFpqVBabmJlVuQ1JawdkMVVXt++vR1fSkzxD2OADurx63sqsXk+v01T1t33/VBa3lCneabzVGVWnoJOSOMo1nR0bY34ZLWnY4qV10O0ygzFmyM1Qd+9p4yt9K+83GJzYT8XyLZ4PfyMF7oom3HTS1In7hT0kUzHa4cfa0LfFBU6Y=
  server: https://test.pypi.org/legacy/
